src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Team__c.object
<CustomObject>
    <fields>
        <fullName>Billable_Rate__c</fullName>
        <label>Billable Rate (Per Hour)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Capacity__c</fullName>
        <globalPicklist>Capacity</globalPicklist>
        <label>Capacity</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cost_Rate__c</fullName>
        <label>Cost Rate (Per Hour)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Project_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Member</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Person Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Common_task__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Common task (add to all future projects)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <label>Hourly Rate</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Sheet__c</fullName>
        <label>Time Sheet</label>
        <referenceTo>Time_Sheet2__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <formula>Person__r.User__r.FirstName+&apos; &apos;+Person__r.User__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>User</label>
        <type>Text</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{00000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Sheet2__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Sheet2s_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Time_Sheet2s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Sheet2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Sheet</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestDataUtils.cls
/*******************************************************************************************************
    * @author  : SARAVANAN C
    * @date    : 17 JAN 2017
    * @modified : 17 JAN 2017
    * @group    :  
    * @group-content : 
    * @description : THIS IS TEST DATA UTILS CLASS
********************************************************************************************************/

Public class TestDataUtils {
    
    /*******************************************************************************************************
    * @description : PROJECT RECORDS
    * @param :  
    * @param : 
    * @return : 
    * @example :  
    *  
    *******************************************************************************************************/
        
    public static  Project__c getProject() {
         
         Project__c Project = new Project__c( 
             Name='Salesforce Project' ,
             Project_Manager__c = UserInfo.getUserid()
         );
         
         insert project ;
         
        return project ;           
    }
    
    
    public static Project_Team__c getProjectTeam() {
         
         Project_Team__c ProjectTeam = new Project_Team__c ( 
             
             Project__c = TestDataUtils.getProject().Id ,
             Capacity__c = '40',
             Billable_Rate__c = 50,
             Cost_Rate__c = 40,
             User__c = UserInfo.getUserid()
         );
          
        insert  ProjectTeam ;
        return ProjectTeam ;           
    }
    
    
    public static Task__c getTask() {
         
         Task__c Task = new Task__c ( 
             
             Name = 'Customization',
             Project__c = TestDataUtils.getProject().Id ,
             Hourly_Rate__c = 50,
             Common_task__c = True 
         );
          
         insert  Task ;
        return Task ;           
    }
    
    Public static Time_Sheet2__c getTimeSheet() {
         
         Time_Sheet2__c TimeSheet = new Time_Sheet2__c ( 
             
             Start_Date__c = Date.Today(),
             Project__c = TestDataUtils.getProject().Id ,
             End_Date__c = Date.Today().adddays(3),
             Project_Manager__c = UserInfo.getUserid() ,
             User__c = UserInfo.getUserid()
         );
          
        insert TimeSheet ; 
        return TimeSheet ;           
    }
    
    Public static Time_Entry__c getTimeEntry() {
         
         Time_Entry__c TimeEntry = new Time_Entry__c ( 
             
             Date__c = Date.Today(),
             Project__c = TestDataUtils.getProject().Id ,
             Task__c = TestDataUtils.getTask().Id ,
             Time_Sheet__c = TestDataUtils.getTimeSheet().Id
         );
          
        insert TimeEntry ; 
        return TimeEntry ;           
    }
    
    
 
  
}