src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Team__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Project_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Member</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Person Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Timer_Status__c</fullName>
        <label>Timer Status</label>
        <picklist>
            <picklistValues>
                <fullName>Running</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Paused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stopped</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>TE-{00000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Sheet2__c.object
<CustomObject>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Sheet2s_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Time_Sheet2s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Time Sheet</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestOverallCodeCoverage.cls
/*******************************************************************************************************
    * @author  : SARAVANAN C
    * @date    : 17 JAN 2017
    * @modified : 17 JAN 2017
    * @group    :  
    * @group-content : 
    * @description : CODE COVERAGE CLASS 
********************************************************************************************************/

@isTest
private class TestOverallCodeCoverage {
  
   
    static testMethod void Project() {
        //Create Dependent Datas
        
        
        Test.startTest();
        
        //Project and Project Team Member
        Project_Team__c projectTeam = TestDataUtils.getProjectTeam();
        
        //Task
        Task__c Task = TestDataUtils.getTask();
        
        //Time Sheet
        Time_Sheet2__c TimeSheet = TestDataUtils.getTimeSheet();
        
        //Time Sheet
        Time_Entry__c TimeEntry = TestDataUtils.getTimeEntry();
        
        TimeEntry.Timer_Status__c = 'Paused' ;
        Update TimeEntry ;
        
        System.assertEquals(TimeEntry.Timer_Status__c, 'Paused');
        
        TimeEntry.Timer_Status__c = 'Running' ;
        Update TimeEntry ;
        
        System.assertEquals(TimeEntry.Timer_Status__c, 'Running');
        
        Project__c Proj = TestDataUtils.getProject();
        Proj.Project_Manager__c = NULL ;
        Update Proj ;
        
        Proj.Project_Manager__c = UserInfo.getUserid() ;
        Update Proj ;
        
        TimerTrackerCont timeTrackerCont = New TimerTrackerCont ();
        timeTrackerCont.getProjects();
        timeTrackerCont.getTasks();
        timeTrackerCont.getTimeSheets();
            
        Test.stopTest();
      
    }
    
     
}