src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Team__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Project_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Member</label>
    <nameField>
        <displayFormat>PN-{0000}</displayFormat>
        <label>Person Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Team</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Time_Sheet2__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project User</label>
        <referenceTo>Project_Team__c</referenceTo>
        <relationshipName>Time_Sheet2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Time_Sheet2s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Time_Sheet2s</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Sheet</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchandScheduleWeeklyTimeSheets.cls
/*******************************************************************************************************
    * @author  : SARAVANAN C
    * @date    : 16 JAN 2017
    * @modified : 16 JAN 2017
    * @group    :  
    * @group-content : 
    * @description : THIS IS BATCHABLE AND SCHEDULE CLASS, OBJECTIVE - A NEW TIMESHEET IS AUTO GENERATED  FOR EACH WEEK IN ADVANCE OVER SUNDAY NIGHT   
********************************************************************************************************/

global with sharing class BatchandScheduleWeeklyTimeSheets implements Schedulable, Database.Batchable<sObject> {

    
  
   /*******************************************************************************************************
    * @description : BATCH CLASS START METHOD, QUERY THE PROJEC TEAM RECORDS (PROJECT USERS)  
    * @param : 
    * @param : 
    * @return : QUERY LOCATOR
    * @example :   
    *  
    *******************************************************************************************************/
    global Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'Select User__c, Project__c FROM Project_Team__c ';
        return Database.getQueryLocator(query);
    }

 
   /*******************************************************************************************************
    * @description : BATCH CLASS EXECUTE METHOD, PROCESS OVER THE PROJECT TEAM RECORDS AND CREATE TIME SHEET FOR THESE USERS  
    * @param : 
    * @param : 
    * @return :  
    * @example :   
    *  
    *******************************************************************************************************/
   global void execute(Database.BatchableContext BC, List<Project_Team__c> scope){
       
       //LIST COLLECTION OF NEW TIMESHEETS
       List<Time_sheet2__c> newTimesheets = new List<Time_sheet2__c>();
       
       //ITERATE OVER THE PROJECT USER RECORDS
       for ( Project_Team__c p : scope ){
           
           newTimesheets.add( New Time_sheet2__c ( 
               Project__c    = p.Project__c, 
               Start_Date__c = Date.today().toStartOfWeek(),
               End_Date__c   = Date.today().toStartOfWeek().addDays(6),
               Project_User__c    = p.id
           ));
       }
       
       insert newTimesheets ;
       
   }
    
   
   /*******************************************************************************************************
    * @description : BATCH CLASS FINISH METHOD, NOT IN SCOPE. NEEDS TO BE EXTENDED WITH EMAIL OR LOGS CREATION TO TRACK THE SUCCESS AND FAILURES  
    * @param : 
    * @param : 
    * @return :  
    * @example :   
    *  
    *******************************************************************************************************/
    global void finish(Database.BatchableContext BC){
   
   }
   
   /*******************************************************************************************************
    * @description : SCHEDULABLE METHOD, METHOD WILL ENABLE THIS CLASS AS SCHEDULABLE  
    * @param : 
    * @param : 
    * @return : QUERY LOCATOR
    * @example :   
    *  
    *******************************************************************************************************/
   global void execute(SchedulableContext scMain) {
       
        Database.executeBatch(new BatchandScheduleWeeklyTimeSheets());
   
   }
    
     
    
}